defaults:
  - _self_
  - model: minilm-cos
  - attack: ours
  - core_objective: retrieval
  - dataset: msmarco-test  # to attack
  - constraints: as-suffix-tox
  - cover_alg: kmeans

# General config:
batch_size: 512  # technical parameter, to control the memory usage
time_limit_in_seconds: 7200  # technical parameter, to control the running time
random_seed: 42
log_to_wandb: True
skip_if_cached: True
exp_tag: 'default'
exp_desc:
